vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: /images/project
            upload_destination: '%kernel.project_dir%/public/uploads/project'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
